<?php

namespace core\utils;

enum BehaviorEventEnum: int
{
  case BLOCK_BREAK_EVENT = 0;
  case BLOCK_PLACE_EVENT = 1;
  case ENTITY_DAMAGE_BY_CHILD_ENTITY_EVENT = 2;
  case ENTITY_DAMAGE_BY_ENTITY_EVENT = 3;
  case ENTITY_DAMAGE_EVENT = 4;
  case ENTITY_ITEM_PICKUP_EVENT = 5;
  case ENTITY_REGAIN_HEALTH_EVENT = 6;
  case ENTITY_SPAWN_EVENT = 7;
  case ENTITY_TELEPORT_EVENT = 8;
  case PROJECTILE_HIT_ENTITY_EVENT = 9;
  case PROJECTILE_HIT_EVENT = 10;
  case PROJECTILE_LAUNCH_EVENT = 11;
  case INVENTORY_TRANSACTION_EVENT = 12;
  case PLAYER_DROP_ITEM_EVENT = 13;
  case PLAYER_INTERACT_EVENT = 14;
  case PLAYER_ITEM_CONSUME_EVENT = 15;
  case PLAYER_ITEM_USE_EVENT = 16;
  case PLAYER_TOGGLE_FLIGHT_EVENT = 17;
  case DATA_PACKET_RECEIVE_EVENT = 18;
  case PLAYER_JUMP_EVENT = 19;
  case BUCKET_EMPTY_EVENT = 20;
  case BUCKET_FILL_EVENT = 21;
}
